# -*- coding: utf-8 -*-
"""ElementosFinitos.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zOVoGyeMkYhIqanDvWbdLY52I0KlvhU1
"""

import numpy as np
  import csv
  import matplotlib.pylab as plt

  with open("/content/extract.0.csv",'r') as i:           #open a file in directory of this script for reading 
      rawdata = list(csv.reader(i,delimiter=","))   #make a list of data in file
  exampledata = np.array(rawdata[1:],dtype=np.float64)    #convert to data array

  with open("/content/extract.1.csv",'r') as i: 
      dataf1 = list(csv.reader(i,delimiter=","))
  exampledata1 = np.array(dataf1[1:],dtype=np.float64)    #convert to data array

  with open("/content/extract.2.csv",'r') as i: 
      dataf2 = list(csv.reader(i,delimiter=","))
  exampledata2 = np.array(dataf2[1:],dtype=np.float64)    #convert to data array

  with open("/content/extract.3.csv",'r') as i: 
      dataf3 = list(csv.reader(i,delimiter=","))
  exampledata3 = np.array(dataf3[1:],dtype=np.float64)    #convert to data array

  with open("/content/extract.4.csv",'r') as i: 
      dataf4 = list(csv.reader(i,delimiter=","))
  exampledata4 = np.array(dataf4[1:],dtype=np.float64)    #convert to data array

  with open("/content/extract.5.csv",'r') as i: 
      dataf5 = list(csv.reader(i,delimiter=","))
  exampledata5 = np.array(dataf5[1:],dtype=np.float64)    #convert to data array

  with open("/content/extract.6.csv",'r') as i: 
      dataf6 = list(csv.reader(i,delimiter=","))
  exampledata6 = np.array(dataf6[1:],dtype=np.float64)    #convert to data array

  with open("/content/extract.7.csv",'r') as i: 
      dataf7 = list(csv.reader(i,delimiter=","))
  exampledata7 = np.array(dataf7[1:],dtype=np.float64)    #convert to data array

  with open("/content/extract.8.csv",'r') as i: 
      dataf8 = list(csv.reader(i,delimiter=","))
  exampledata8 = np.array(dataf8[1:],dtype=np.float64)    #convert to data array

  with open("/content/extract.9.csv",'r') as i: 
      dataf9 = list(csv.reader(i,delimiter=","))
  exampledata9 = np.array(dataf9[1:],dtype=np.float64)    #convert to data array

  xdata = exampledata[:,9]
  ydata = exampledata[:,0]

  xdata1 = exampledata1[:,9]
  ydata1 = exampledata1[:,0]

  xdata2 = exampledata2[:,9]
  ydata2 = exampledata2[:,0]

  xdata3 = exampledata3[:,9]
  ydata3 = exampledata3[:,0]

  xdata4 = exampledata4[:,9]
  ydata4 = exampledata4[:,0]

  xdata5 = exampledata5[:,9]
  ydata5 = exampledata5[:,0]

  xdata6 = exampledata6[:,9]
  ydata6 = exampledata6[:,0]

  xdata7 = exampledata7[:,9]
  ydata7 = exampledata7[:,0]
  
  xdata8 = exampledata8[:,9]
  ydata8 = exampledata8[:,0]
  
  xdata9 = exampledata9[:,9]
  ydata9 = exampledata9[:,0]


  plt.figure(1,dpi=120)
  plt.title('Perfil de Pressão em x:')
  plt.yscale('linear')
  plt.xscale('linear')
  plt.xlabel('x')
  plt.ylabel('p')
  plt.plot(xdata,ydata,label="Experimental Data")
  plt.plot(xdata1,ydata1,label="Experimental Data")
  plt.plot(xdata2,ydata2,label="Experimental Data")
  plt.plot(xdata3,ydata3,label="Experimental Data")
  plt.plot(xdata4,ydata4,label="Experimental Data")
  plt.plot(xdata5,ydata5,label="Experimental Data")
  plt.plot(xdata6,ydata6,label="Experimental Data")
  plt.plot(xdata7,ydata7,label="Experimental Data")
  plt.plot(xdata8,ydata8,label="Experimental Data")
  plt.plot(xdata9,ydata9,label="Experimental Data")

import numpy as np
  import csv
  import matplotlib.pylab as plt

  with open("/content/extract.0.csv",'r') as i:           #open a file in directory of this script for reading 
      rawdata = list(csv.reader(i,delimiter=","))   #make a list of data in file
  exampledata = np.array(rawdata[1:],dtype=np.float64)    #convert to data array

  with open("/content/extract.1.csv",'r') as i: 
      dataf1 = list(csv.reader(i,delimiter=","))
  exampledata1 = np.array(dataf1[1:],dtype=np.float64)    #convert to data array

  with open("/content/extract.2.csv",'r') as i: 
      dataf2 = list(csv.reader(i,delimiter=","))
  exampledata2 = np.array(dataf2[1:],dtype=np.float64)    #convert to data array

  with open("/content/extract.3.csv",'r') as i: 
      dataf3 = list(csv.reader(i,delimiter=","))
  exampledata3 = np.array(dataf3[1:],dtype=np.float64)    #convert to data array

  with open("/content/extract.4.csv",'r') as i: 
      dataf4 = list(csv.reader(i,delimiter=","))
  exampledata4 = np.array(dataf4[1:],dtype=np.float64)    #convert to data array

  with open("/content/extract.5.csv",'r') as i: 
      dataf5 = list(csv.reader(i,delimiter=","))
  exampledata5 = np.array(dataf5[1:],dtype=np.float64)    #convert to data array

  with open("/content/extract.6.csv",'r') as i: 
      dataf6 = list(csv.reader(i,delimiter=","))
  exampledata6 = np.array(dataf6[1:],dtype=np.float64)    #convert to data array

  with open("/content/extract.7.csv",'r') as i: 
      dataf7 = list(csv.reader(i,delimiter=","))
  exampledata7 = np.array(dataf7[1:],dtype=np.float64)    #convert to data array

  with open("/content/extract.8.csv",'r') as i: 
      dataf8 = list(csv.reader(i,delimiter=","))
  exampledata8 = np.array(dataf8[1:],dtype=np.float64)    #convert to data array

  with open("/content/extract.9.csv",'r') as i: 
      dataf9 = list(csv.reader(i,delimiter=","))
  exampledata9 = np.array(dataf9[1:],dtype=np.float64)    #convert to data array

  xdata = exampledata[:,10]
  ydata = exampledata[:,0]

  xdata1 = exampledata1[:,10]
  ydata1 = exampledata1[:,0]

  xdata2 = exampledata2[:,10]
  ydata2 = exampledata2[:,0]

  xdata3 = exampledata3[:,10]
  ydata3 = exampledata3[:,0]

  xdata4 = exampledata4[:,10]
  ydata4 = exampledata4[:,0]

  xdata5 = exampledata5[:,10]
  ydata5 = exampledata5[:,0]

  xdata6 = exampledata6[:,10]
  ydata6 = exampledata6[:,0]

  xdata7 = exampledata7[:,10]
  ydata7 = exampledata7[:,0]
  
  xdata8 = exampledata8[:,10]
  ydata8 = exampledata8[:,0]
  
  xdata9 = exampledata9[:,10]
  ydata9 = exampledata9[:,0]


  plt.figure(1,dpi=120)
  plt.title('Perfil de Pressão em y :')
  plt.yscale('linear')
  plt.xscale('linear')
  plt.xlabel('y')
  plt.ylabel('p')
  plt.plot(xdata,ydata,label="Experimental Data")
  plt.plot(xdata1,ydata1,label="Experimental Data")
  plt.plot(xdata2,ydata2,label="Experimental Data")
  plt.plot(xdata3,ydata3,label="Experimental Data")
  plt.plot(xdata4,ydata4,label="Experimental Data")
  plt.plot(xdata5,ydata5,label="Experimental Data")
  plt.plot(xdata6,ydata6,label="Experimental Data")
  plt.plot(xdata7,ydata7,label="Experimental Data")
  plt.plot(xdata8,ydata8,label="Experimental Data")
  plt.plot(xdata9,ydata9,label="Experimental Data")



import numpy as np
  import csv
  import matplotlib.pylab as plt

  with open("/content/extract.0.csv",'r') as i:           #open a file in directory of this script for reading 
      rawdata = list(csv.reader(i,delimiter=","))   #make a list of data in file
  exampledata = np.array(rawdata[1:],dtype=np.float64)    #convert to data array

  with open("/content/extract.1.csv",'r') as i: 
      dataf1 = list(csv.reader(i,delimiter=","))
  exampledata1 = np.array(dataf1[1:],dtype=np.float64)    #convert to data array

  with open("/content/extract.2.csv",'r') as i: 
      dataf2 = list(csv.reader(i,delimiter=","))
  exampledata2 = np.array(dataf2[1:],dtype=np.float64)    #convert to data array

  with open("/content/extract.3.csv",'r') as i: 
      dataf3 = list(csv.reader(i,delimiter=","))
  exampledata3 = np.array(dataf3[1:],dtype=np.float64)    #convert to data array

  with open("/content/extract.4.csv",'r') as i: 
      dataf4 = list(csv.reader(i,delimiter=","))
  exampledata4 = np.array(dataf4[1:],dtype=np.float64)    #convert to data array

  with open("/content/extract.5.csv",'r') as i: 
      dataf5 = list(csv.reader(i,delimiter=","))
  exampledata5 = np.array(dataf5[1:],dtype=np.float64)    #convert to data array

  with open("/content/extract.6.csv",'r') as i: 
      dataf6 = list(csv.reader(i,delimiter=","))
  exampledata6 = np.array(dataf6[1:],dtype=np.float64)    #convert to data array

  with open("/content/extract.7.csv",'r') as i: 
      dataf7 = list(csv.reader(i,delimiter=","))
  exampledata7 = np.array(dataf7[1:],dtype=np.float64)    #convert to data array

  with open("/content/extract.8.csv",'r') as i: 
      dataf8 = list(csv.reader(i,delimiter=","))
  exampledata8 = np.array(dataf8[1:],dtype=np.float64)    #convert to data array

  with open("/content/extract.9.csv",'r') as i: 
      dataf9 = list(csv.reader(i,delimiter=","))
  exampledata9 = np.array(dataf9[1:],dtype=np.float64)    #convert to data array

  xdata = exampledata[:,11]
  ydata = exampledata[:,0]

  xdata1 = exampledata1[:,11]
  ydata1 = exampledata1[:,0]

  xdata2 = exampledata2[:,11]
  ydata2 = exampledata2[:,0]

  xdata3 = exampledata3[:,11]
  ydata3 = exampledata3[:,0]

  xdata4 = exampledata4[:,11]
  ydata4 = exampledata4[:,0]

  xdata5 = exampledata5[:,11]
  ydata5 = exampledata5[:,0]

  xdata6 = exampledata6[:,11]
  ydata6 = exampledata6[:,0]

  xdata7 = exampledata7[:,11]
  ydata7 = exampledata7[:,0]
  
  xdata8 = exampledata8[:,11]
  ydata8 = exampledata8[:,0]
  
  xdata9 = exampledata9[:,11]
  ydata9 = exampledata9[:,0]


  plt.figure(1,dpi=120)
  plt.title('Perfil de Pressão em z:')
  plt.yscale('linear')
  plt.xscale('linear')
  plt.xlabel('z')
  plt.ylabel('p')
  plt.plot(xdata,ydata,label="Experimental Data")
  plt.plot(xdata1,ydata1,label="Experimental Data")
  plt.plot(xdata2,ydata2,label="Experimental Data")
  plt.plot(xdata3,ydata3,label="Experimental Data")
  plt.plot(xdata4,ydata4,label="Experimental Data")
  plt.plot(xdata5,ydata5,label="Experimental Data")
  plt.plot(xdata6,ydata6,label="Experimental Data")
  plt.plot(xdata7,ydata7,label="Experimental Data")
  plt.plot(xdata8,ydata8,label="Experimental Data")
  plt.plot(xdata9,ydata9,label="Experimental Data")

import numpy as np
  import csv
  import matplotlib.pylab as plt

  with open("/content/extract.0.csv",'r') as i:           #open a file in directory of this script for reading 
      rawdata = list(csv.reader(i,delimiter=","))   #make a list of data in file
  exampledata = np.array(rawdata[1:],dtype=np.float64)    #convert to data array

  with open("/content/extract.1.csv",'r') as i: 
      dataf1 = list(csv.reader(i,delimiter=","))
  exampledata1 = np.array(dataf1[1:],dtype=np.float64)    #convert to data array

  with open("/content/extract.2.csv",'r') as i: 
      dataf2 = list(csv.reader(i,delimiter=","))
  exampledata2 = np.array(dataf2[1:],dtype=np.float64)    #convert to data array

  with open("/content/extract.3.csv",'r') as i: 
      dataf3 = list(csv.reader(i,delimiter=","))
  exampledata3 = np.array(dataf3[1:],dtype=np.float64)    #convert to data array

  with open("/content/extract.4.csv",'r') as i: 
      dataf4 = list(csv.reader(i,delimiter=","))
  exampledata4 = np.array(dataf4[1:],dtype=np.float64)    #convert to data array

  with open("/content/extract.5.csv",'r') as i: 
      dataf5 = list(csv.reader(i,delimiter=","))
  exampledata5 = np.array(dataf5[1:],dtype=np.float64)    #convert to data array

  with open("/content/extract.6.csv",'r') as i: 
      dataf6 = list(csv.reader(i,delimiter=","))
  exampledata6 = np.array(dataf6[1:],dtype=np.float64)    #convert to data array

  with open("/content/extract.7.csv",'r') as i: 
      dataf7 = list(csv.reader(i,delimiter=","))
  exampledata7 = np.array(dataf7[1:],dtype=np.float64)    #convert to data array

  with open("/content/extract.8.csv",'r') as i: 
      dataf8 = list(csv.reader(i,delimiter=","))
  exampledata8 = np.array(dataf8[1:],dtype=np.float64)    #convert to data array

  with open("/content/extract.9.csv",'r') as i: 
      dataf9 = list(csv.reader(i,delimiter=","))
  exampledata9 = np.array(dataf9[1:],dtype=np.float64)    #convert to data array

  xdata = exampledata[:,9]
  ydata = exampledata[:,1]

  xdata1 = exampledata1[:,9]
  ydata1 = exampledata1[:,1]

  xdata2 = exampledata2[:,9]
  ydata2 = exampledata2[:,1]

  xdata3 = exampledata3[:,9]
  ydata3 = exampledata3[:,1]

  xdata4 = exampledata4[:,9]
  ydata4 = exampledata4[:,1]

  xdata5 = exampledata5[:,9]
  ydata5 = exampledata5[:,1]

  xdata6 = exampledata6[:,9]
  ydata6 = exampledata6[:,1]

  xdata7 = exampledata7[:,9]
  ydata7 = exampledata7[:,1]
  
  xdata8 = exampledata8[:,9]
  ydata8 = exampledata8[:,1]
  
  xdata9 = exampledata9[:,9]
  ydata9 = exampledata9[:,1]


  plt.figure(1,dpi=120)
  plt.title('Perfil de Velocidade x em x:')
  plt.yscale('linear')
  plt.xscale('linear')
  plt.xlabel('x')
  plt.ylabel('v')
  plt.plot(xdata,ydata,label="Experimental Data")
  plt.plot(xdata1,ydata1,label="Experimental Data")
  plt.plot(xdata2,ydata2,label="Experimental Data")
  plt.plot(xdata3,ydata3,label="Experimental Data")
  plt.plot(xdata4,ydata4,label="Experimental Data")
  plt.plot(xdata5,ydata5,label="Experimental Data")
  plt.plot(xdata6,ydata6,label="Experimental Data")
  plt.plot(xdata7,ydata7,label="Experimental Data")
  plt.plot(xdata8,ydata8,label="Experimental Data")
  plt.plot(xdata9,ydata9,label="Experimental Data")

import numpy as np
  import csv
  import matplotlib.pylab as plt

  with open("/content/extract.0.csv",'r') as i:           #open a file in directory of this script for reading 
      rawdata = list(csv.reader(i,delimiter=","))   #make a list of data in file
  exampledata = np.array(rawdata[1:],dtype=np.float64)    #convert to data array

  with open("/content/extract.1.csv",'r') as i: 
      dataf1 = list(csv.reader(i,delimiter=","))
  exampledata1 = np.array(dataf1[1:],dtype=np.float64)    #convert to data array

  with open("/content/extract.2.csv",'r') as i: 
      dataf2 = list(csv.reader(i,delimiter=","))
  exampledata2 = np.array(dataf2[1:],dtype=np.float64)    #convert to data array

  with open("/content/extract.3.csv",'r') as i: 
      dataf3 = list(csv.reader(i,delimiter=","))
  exampledata3 = np.array(dataf3[1:],dtype=np.float64)    #convert to data array

  with open("/content/extract.4.csv",'r') as i: 
      dataf4 = list(csv.reader(i,delimiter=","))
  exampledata4 = np.array(dataf4[1:],dtype=np.float64)    #convert to data array

  with open("/content/extract.5.csv",'r') as i: 
      dataf5 = list(csv.reader(i,delimiter=","))
  exampledata5 = np.array(dataf5[1:],dtype=np.float64)    #convert to data array

  with open("/content/extract.6.csv",'r') as i: 
      dataf6 = list(csv.reader(i,delimiter=","))
  exampledata6 = np.array(dataf6[1:],dtype=np.float64)    #convert to data array

  with open("/content/extract.7.csv",'r') as i: 
      dataf7 = list(csv.reader(i,delimiter=","))
  exampledata7 = np.array(dataf7[1:],dtype=np.float64)    #convert to data array

  with open("/content/extract.8.csv",'r') as i: 
      dataf8 = list(csv.reader(i,delimiter=","))
  exampledata8 = np.array(dataf8[1:],dtype=np.float64)    #convert to data array

  with open("/content/extract.9.csv",'r') as i: 
      dataf9 = list(csv.reader(i,delimiter=","))
  exampledata9 = np.array(dataf9[1:],dtype=np.float64)    #convert to data array

  xdata = exampledata[:,10]
  ydata = exampledata[:,2]

  xdata1 = exampledata1[:,10]
  ydata1 = exampledata1[:,2]

  xdata2 = exampledata2[:,10]
  ydata2 = exampledata2[:,2]

  xdata3 = exampledata3[:,10]
  ydata3 = exampledata3[:,2]

  xdata4 = exampledata4[:,10]
  ydata4 = exampledata4[:,2]

  xdata5 = exampledata5[:,10]
  ydata5 = exampledata5[:,2]

  xdata6 = exampledata6[:,10]
  ydata6 = exampledata6[:,2]

  xdata7 = exampledata7[:,10]
  ydata7 = exampledata7[:,2]
  
  xdata8 = exampledata8[:,10]
  ydata8 = exampledata8[:,2]
  
  xdata9 = exampledata9[:,10]
  ydata9 = exampledata9[:,2]


  plt.figure(1,dpi=120)
  plt.title('Perfil de Velocidade y em y:')
  plt.yscale('linear')
  plt.xscale('linear')
  plt.xlabel('y')
  plt.ylabel('v')
  plt.plot(xdata,ydata,label="Experimental Data")
  plt.plot(xdata1,ydata1,label="Experimental Data")
  plt.plot(xdata2,ydata2,label="Experimental Data")
  plt.plot(xdata3,ydata3,label="Experimental Data")
  plt.plot(xdata4,ydata4,label="Experimental Data")
  plt.plot(xdata5,ydata5,label="Experimental Data")
  plt.plot(xdata6,ydata6,label="Experimental Data")
  plt.plot(xdata7,ydata7,label="Experimental Data")
  plt.plot(xdata8,ydata8,label="Experimental Data")
  plt.plot(xdata9,ydata9,label="Experimental Data")

import numpy as np
  import csv
  import matplotlib.pylab as plt

  with open("/content/extract.0.csv",'r') as i:           #open a file in directory of this script for reading 
      rawdata = list(csv.reader(i,delimiter=","))   #make a list of data in file
  exampledata = np.array(rawdata[1:],dtype=np.float64)    #convert to data array

  with open("/content/extract.1.csv",'r') as i: 
      dataf1 = list(csv.reader(i,delimiter=","))
  exampledata1 = np.array(dataf1[1:],dtype=np.float64)    #convert to data array

  with open("/content/extract.2.csv",'r') as i: 
      dataf2 = list(csv.reader(i,delimiter=","))
  exampledata2 = np.array(dataf2[1:],dtype=np.float64)    #convert to data array

  with open("/content/extract.3.csv",'r') as i: 
      dataf3 = list(csv.reader(i,delimiter=","))
  exampledata3 = np.array(dataf3[1:],dtype=np.float64)    #convert to data array

  with open("/content/extract.4.csv",'r') as i: 
      dataf4 = list(csv.reader(i,delimiter=","))
  exampledata4 = np.array(dataf4[1:],dtype=np.float64)    #convert to data array

  with open("/content/extract.5.csv",'r') as i: 
      dataf5 = list(csv.reader(i,delimiter=","))
  exampledata5 = np.array(dataf5[1:],dtype=np.float64)    #convert to data array

  with open("/content/extract.6.csv",'r') as i: 
      dataf6 = list(csv.reader(i,delimiter=","))
  exampledata6 = np.array(dataf6[1:],dtype=np.float64)    #convert to data array

  with open("/content/extract.7.csv",'r') as i: 
      dataf7 = list(csv.reader(i,delimiter=","))
  exampledata7 = np.array(dataf7[1:],dtype=np.float64)    #convert to data array

  with open("/content/extract.8.csv",'r') as i: 
      dataf8 = list(csv.reader(i,delimiter=","))
  exampledata8 = np.array(dataf8[1:],dtype=np.float64)    #convert to data array

  with open("/content/extract.9.csv",'r') as i: 
      dataf9 = list(csv.reader(i,delimiter=","))
  exampledata9 = np.array(dataf9[1:],dtype=np.float64)    #convert to data array

  xdata = exampledata[:,11]
  ydata = exampledata[:,3]

  xdata1 = exampledata1[:,11]
  ydata1 = exampledata1[:,3]

  xdata2 = exampledata2[:,11]
  ydata2 = exampledata2[:,3]

  xdata3 = exampledata3[:,11]
  ydata3 = exampledata3[:,3]

  xdata4 = exampledata4[:,11]
  ydata4 = exampledata4[:,3]

  xdata5 = exampledata5[:,11]
  ydata5 = exampledata5[:,3]

  xdata6 = exampledata6[:,11]
  ydata6 = exampledata6[:,3]

  xdata7 = exampledata7[:,11]
  ydata7 = exampledata7[:,3]
  
  xdata8 = exampledata8[:,11]
  ydata8 = exampledata8[:,3]
  
  xdata9 = exampledata9[:,11]
  ydata9 = exampledata9[:,3]


  plt.figure(1,dpi=120)
  plt.title('Perfil de Velocidade z em z:')
  plt.yscale('linear')
  plt.xscale('linear')
  plt.xlabel('z')
  plt.ylabel('v')
  plt.plot(xdata,ydata,label="Experimental Data")
  plt.plot(xdata1,ydata1,label="Experimental Data")
  plt.plot(xdata2,ydata2,label="Experimental Data")
  plt.plot(xdata3,ydata3,label="Experimental Data")
  plt.plot(xdata4,ydata4,label="Experimental Data")
  plt.plot(xdata5,ydata5,label="Experimental Data")
  plt.plot(xdata6,ydata6,label="Experimental Data")
  plt.plot(xdata7,ydata7,label="Experimental Data")
  plt.plot(xdata8,ydata8,label="Experimental Data")
  plt.plot(xdata9,ydata9,label="Experimental Data")